export const FETCH_USER = "FETCH_USER";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const CREATE_STREAM = "CREATE_STREAM";
export const SELECT_VIDEO = "SELECT_VIDEO";
export const FETCH_STREAMS = "FETCH_STREAMS";
export const FETCH_STREAM = "FETCH_STREAM";
export const DELETE_STREAM = "DELETE_STREAM";
export const EDIT_STREAM = "EDIT_STREAM";
export const SHOW_MODAL = "SHOW_MODAL";
export const FETCH_VIDEOS = "FETCH_VIDEOS";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const FETCH_AUTH = "FETCH_AUTH";
export const LOGOUT_AUTH = "LOGOUT_AUTH";
export const SIGNUP_CREATE = "SIGNUP_CREATE";
export const MOVE_RIGHT = "MOVE_RIGHT";
export const MOVE_LEFT = "MOVE_LEFT";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOADING_SPINNER = "LOADING_SPINNER";
export const AUTH_ERROR_CLEAR = "AUTH_ERROR_CLEAR";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_TOKEN = "LOGIN_TOKEN";
export const LOGOUT_TOKEN = "LOGOUT_TOKEN";
export const CHECKOUT_JWT = "CHECKOUT_JWT";
export const JWT_AUTH = "JWT_AUTH";
export const JWT_AUTH_LOGOUT = "JWT_AUTH_LOGOUT";
export const TWITCH_HOME_REQUEST = "TWITCH_HOME_REQUEST";
export const TWITCH_HOME_SUCCESS = "TWITCH_HOME_SUCCESS";
export const TWITCH_HOME_FAILURE = "TWITCH_HOME_FAILURE";
export const TWITCH_CATEGORY_MORE_REQUEST = "TWITCH_CATEGORY_MORE_REQUEST";
export const TWITCH_CATEGORY_MORE_SUCCESS = "TWITCH_CATEGORY_MORE_SUCCESS";
export const TWITCH_CATEGORY_MORE_FAILURE = "TWITCH_CATEGORY_MORE_FAILURE";
export const TWITCH_LIVE_REVEAL = "TWITCH_LIVE_REVEAL";
export const TWITCH_LIVE_MORE_REQUEST = "TWITCH_LIVE_MORE_REQUEST";
export const TWITCH_LIVE_MORE_SUCCESS = "TWITCH_LIVE_MORE_SUCCESS";
export const TWITCH_LIVE_MORE_FAILURE = "TWITCH_LIVE_MORE_FAILURE";
export const TWITCH_GAMES_MORE_REQUEST = "TWITCH_GAMES_MORE_REQUEST";
export const TWITCH_GAMES_MORE_SUCCESS = "TWITCH_GAMES_MORE_SUCCESS";
export const TWITCH_GAMES_MORE_FAILURE = "TWITCH_GAMES_MORE_FAILURE";


// export const VERIFY_JWT ="VERIFY_JWT";
//right after const ctrl + D * 4
//right shift twice
//ctrl + shift + right shitft
